### ISSUE TITLE
Airport look up not working

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1590]
The airport look up feature in new airport page is not functioning 

**Version**
Latest dev 7f346a

**To Reproduce**
1. Go to airports
2. Click on add new airport
3. Enter a new airport and press red lookup text
4. nothing happens

**Expected behavior**
It should populate the required fields

Looking at the logs cannot see anything connected it does show this error at the bottom of the log but not timed to the above attempt.
[2023-08-19 09:10:51] production.ERROR: API Error

**Comment by FatihKoz** [comment]
Confirmed, previous builds was working ok. 
Tested with `7.0.0-dev+230801.e24df8` and was ok, updated to `7.0.0-dev+230818.7f346a` and tried, saw the error.

[laravel-2023-08-19.log](https://github.com/nabeelio/phpvms/files/12386426/laravel-2023-08-19.log)

**Comment by ItzSteveHuh** [comment]
Any update for this issue?

**Comment by nabeelio** [comment]
I think this was already fixed

**Comment by ItzSteveHuh** [comment]
> I think this was already fixed

I'm still having the same issue as FaithKoz mentioned above after version the latest dev version 7.0.0-dev+230818.7f346a.
Here's my latest log after attempting an airport lookup. 
[laravel-2023-08-23.log](https://github.com/nabeelio/phpvms/files/12414122/laravel-2023-08-23.log)

**Comment by dougjuk** [comment]
As far as I am aware we had fixed this.  But it needs to have later version than Stephen is mentioning...  Also people need to update their app.blad.php files if they have clone themes.
