### ISSUE TITLE
Flight ID's and Airport ICAO's not clickable on airport page

### ISSUE THREAD

**Issue by voipmeister** [nabeelio/phpvms#419]
![airport](https://user-images.githubusercontent.com/12763807/67625493-34902200-f83f-11e9-8f04-e19f54058917.jpg)
**Describe the bug**
When opening <site>/airports/SKBO, the airport page (in this case for SKBO) is opened along with METAR info and in- and outbound flights. The flight id's and ICAO's listed are not clickable, while I feel they should be (since they have a different color). I would really like them to be clickable because it allows me to book connecting flights.

**Version**
version 7.0.0 (build 191023.12679e)

**To Reproduce**
1. Go to '<site>/airports/SKBO'
2. Scroll down to 'in- and outbound flights'
4. Try to click on a flight ID or ICAO

**Expected behavior**
I would really like them to be clickable because it allows me to book connecting flights.

**Screenshots**
Screenshot added.

**Additional context**
None.

**Comment by voipmeister** [comment]
Used browser: Firefox 70 on Ubuntu 18.04 LTS

**Comment by voipmeister** [comment]
I don't have chrome installed, but will do so and check.

**Comment by voipmeister** [comment]
In Chrome, it's working.

**Comment by nabeelio** [comment]
Thanks for checking, I'll have to setup Firefox and figure out why.

**Comment by voipmeister** [comment]
No problem. I have this on Firefox 70 on macOS + Ubuntu 18.04 LTS. Also checked Safari on macOS (will add version later): no problem.

**Comment by nabeelio** [comment]
This should hopefully be fixed in the latest dev. If you can check, that'd be great!

**Comment by voipmeister** [comment]
I'll check later today!

**Comment by voipmeister** [comment]
Bug was in 7.0.0+191023.12679e, I installed 7.0.0+191030.70d43e. Unfortunately, it's still present.

**Comment by voipmeister** [comment]
Investigated some more. Removing `table-condensed` from the table's class fixes it for me in Firefox 70. Please see the screenshot.

<img width="1318" alt="Screenshot 2019-10-30 at 22 18 17" src="https://user-images.githubusercontent.com/12763807/67899790-55b88180-fb63-11e9-88c4-e3997670ed21.png">

**Comment by nabeelio** [comment]
Does it look OK non-condensed?

**Comment by voipmeister** [comment]
It looks like this, which is fine I think. Non-breaking lines for the airport names would be better. I can check for that as well.

<img width="1440" alt="Screenshot 2019-10-31 at 17 01 39" src="https://user-images.githubusercontent.com/12763807/67966217-c8793980-fc03-11e9-8e0a-ba2d2abf9e6e.png">

**Comment by nabeelio** [comment]
Yeah, that'd be great, thank you!

**Comment by nabeelio** [comment]
Looks great!
