### ISSUE TITLE
Public Pages

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#708]
It appears that even when you have a page set as public, it still requires a login to view the page.

**Comment by nickkecooper** [comment]
Added the following code ``` Route::get('p/{slug}', 'PageController@show')->name('pages.show'); ``` to RouteServiceProvider.php within

```
            Route::group([
                'namespace' => 'Frontend',
                'prefix'    => '',
                'as'        => 'frontend.',
            ], function () {
```

This seemed to fix the issue. Not sure if its a concrete fix.

**Comment by ollimaz** [comment]
Hi,
> 
> 
> Added the following code `Route::get('p/{slug}', 'PageController@show')->name('pages.show');` to RouteServiceProvider.php within
> 
> ```
>             Route::group([
>                 'namespace' => 'Frontend',
>                 'prefix'    => '',
>                 'as'        => 'frontend.',
>             ], function () {
> ```
> 
> This seemed to fix the issue. Not sure if its a concrete fix.

This Fix causes that pages that aren't checked as public get public too. So every page if public or not gets accessible through /p/{pageid}.



> 
> 
> It appears that even when you have a page set as public, it still requires a login to view the page.

I would like to add that the pages marked as public aren't shown in the nav menu either;(

I didn't have enough time to check on that, but it seems that `$moduleSvc->getFrontendLinks($logged_in=false)` in nav.blade.php doesn't seem to work right

**Comment by ollimaz** [comment]
> 
> 
> It appears that even when you have a page set as public, it still requires a login to view the page.

The main problem is that after changing the settings of a page the cache don't automatically clears. So that the change hasn't any affect. 

You need to reset the cache after setting a page to public. Adding `Route::get('p/{slug}', 'PageController@show')->name('pages.show');` is making every page public. 

The problem for me is just, that the pages arent' displayed in the menu when not logged in and set to public.

**Comment by nabeelio** [comment]
This is fixed in https://github.com/nabeelio/phpvms/pull/749 and will be avail in dev. Note the changes to `nav.blade.php`.

**Comment by ollimaz** [comment]
> 
> 
> It appears that even when you have a page set as public, it still requires a login to view the page.

This still isn't fixed. Public pages are now shown in the navigation. But it is still required to login to view them...
